## learn about numpy with chai aur code

In [1]:
import numpy as np

### creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_1d)

1D array:  [1 2 3 4 5]
2D array:  [1 2 3 4 5]


### List vs numpy array

In [6]:
py_list = [1,2,3]
print("python list multiplication ", py_list * 2)

np_array = np.array([1,2,3]) # element wise multiplication
print("python array multiplication ", np_array * 2)

python list multiplication  [1, 2, 3, 1, 2, 3]
python array multiplication  [2 4 6]


In [7]:
import time
start = time.time()
py_list = [i*2 for i in range(100000000)]
print("\n List operation time ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time ", time.time() - start)


 List operation time  16.052150011062622

 Numpy operation time  0.07041740417480469


### creating array from scratch

In [15]:
zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

ones = np.ones((3, 4))
print("ones array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array \n", random)

sequence = np.arange(0, 11, 2)
print("sequence array \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array 
 [[0.06188604 0.63878136 0.52356483]
 [0.67759391 0.50684632 0.1041957 ]]
sequence array 
 [ 0  2  4  6  8 10]


### Vector, Matrices, Tensom

In [18]:
vector = np.array([1, 2, 3])
print("Vecotor: ", vector)

matrices = np.array([[1, 2, 3],
                     [4, 5, 6]])
print("Matrices: ", matrices)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vecotor:  [1 2 3]
Matrices:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [24]:
arr = np.array([[1, 2, 3],
                [4, 5, 2]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("size", arr.size)
print("DType", arr.dtype)

Shape (2, 3)
Dimension 2
size 6
DType int64


### Array Reshaping

In [29]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array: ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (return view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
